### ISSUE TITLE
А почему решено писать на JQuery?

### ISSUE THREAD

**Issue by veranikashneidzer** [js-day/js-day#1]
_Целый день пить пиво и писать на jquery_

Предлагаю запилить js-challenge в 10 дней, но писать не на JQuery, а на всех js подобных языках. И сделать какой-нибудь сайт с кучей мозголомных задачек на разных языках и библиотеках, пошедших от JS . Или начать это пока просто на гитхабе. Как список тасок с курсов. 

А то не совсем понятно, что именно будем писать. И почему jquery? Может кто-то хочет поугарать и писать 10 дней что-то на FP или найти громадный код и похудеть-его-к-лету с помощью Lodash.

И почему пиво? И почему JS-day, а не ECMA-day/ES-day?

**Comment by dzmitry-varabei** [comment]
привет! в данный момент просто собираем идеи, ближе к маю будем думать/обсуждать что пойдет в релиз :)
